  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    ports:
      - "5354:53/tcp"
      - "5354:53/udp"
    volumes:
      - ./volumes/unbound/:/opt/unbound/etc/unbound/
    restart: unless-stopped
